packages:
  - apps/*
  - packages/*

allowBuilds:
  '@prisma/engines': true
  esbuild: true
  prisma: true
  sharp: true

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@tailwindcss/oxide'
  - esbuild
  - prisma
  - sharp
