packages:
  - apps/*
  - packages/*

allowBuilds:
  '@prisma/engines': set this to true or false
  esbuild: set this to true or false
  prisma: set this to true or false
  sharp: set this to true or false

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@tailwindcss/oxide'
  - esbuild
  - prisma
  - sharp
